[WIP] build static libraries
conda-forge/folly-feedstock pull request #128
Opened 2023-08-22 07:45 UTC by DerThorsten

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-08-22 08:59 UTC, DerThorsten commented
@conda-forge-admin, please rerender

2023-08-23 11:06 UTC, xhochy requested changes
Please have a look at `libprotobuf`. This has some nice further features that ensure that the CMakeConfig is correct in the static case.

2023-08-23 11:06 UTC, xhochy commented on recipe/build_folly.sh
> +then
`PKG_NAME` should always be defined.
```suggestion
if [[ "${PKG_NAME}" == "folly" ]]; then
```

2023-08-23 11:06 UTC, xhochy commented on recipe/build_folly.sh
> +$BUILD_PREFIX/bin/cmake --build . --parallel
This should not be necessary. If a different CMake (not the one in $BUILD_PREFIX) is picked up, this is an indication that something else in your environment is broken.
```suggestion
cmake --build . --parallel 
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +{% set build_number = 1 %}
Please keep the build number as plain YAML
```suggestion
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +  number: {{ build_number }}
```suggestion
  number: 1
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +  # See: https://github.com/facebook/folly/#build-notes
This comment is covered by the run_exports.
```suggestion
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +      number: {{ build_number }}
```suggestion
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +      number: {{ build_number }}
```suggestion
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +        - zstd
Please deduplicate the headers, they should only be in the shared build.
```suggestion
        - zstd
        - {{ pin_subpackage('folly', exact=True) }}
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +        - snappy
```suggestion
        - snappy
        - {{ pin_subpackage('folly', exact=True) }}
```

2023-08-23 11:06 UTC, xhochy commented on recipe/meta.yaml
> +        - test -f ${PREFIX}/lib/libfolly${SHLIB_EXT}              # [unix]
```suggestion
        - test -f ${PREFIX}/lib/libfolly${SHLIB_EXT}              # [unix]
        - test ! -f ${PREFIX}/lib/libfolly.a              # [unix]
```

2024-02-26 10:48 UTC, jjerphan commented
Closing as agreed with @DerThorsten since we do not need the static libraries anymore.

2024-02-26 10:48 UTC, closed without merging